In [ ]:
# Exercise 1: Getting & Knowing Your Data (chipo)

import pandas as pd

url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

# Retrieve the dataset from this link and assign it to a variable ‘chipo’.
print(chipo.head(10))

# Display the first 10 rows of ‘chipo’ using the head() function.
print(chipo.info())

# Determine the total number of entries (rows) in ‘chipo’ using shape or info().
print(chipo.shape)

# Use columns to print all the column names.
print(chipo.columns)

# Utilize index to understand how the DataFrame is indexed.
print(chipo.index)

# Use the value_counts() method on the ‘item_name’ column to find the most ordered item
print(chipo['item_name'].value_counts())

# Convert ‘item_price’ to a float datatype using apply() and lambda.
# (Hint: You’ll need to remove the ‘$’ from the prices first)
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x.replace('$', '')))

# Calculate the total revenue for the dataset by summing the ‘item_price’ column
print(chipo['item_price'].mean())

# Find the total number of orders by using the nunique() function on the ‘order_id’ column.
print(chipo['order_id'].nunique())

# Compute the average order value by dividing the total revenue by the number of orders.
order_totals = chipo.groupby('order_id')['item_price'].sum()
average_order_value = order_totals.mean()
print(average_order_value)

# Determine the total number of unique items sold using the nunique() function on the ‘item_name’ column.
print(chipo['item_name'].nunique())

In [ ]:
# Exercise_XP_2
import pandas as pd

url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

products_over_10 = chipo[chipo['item_price'] > 10]

count_over_10 = products_over_10.shape[0]

print(count_over_10)

In [ ]:
# Exercise_XP_3

import pandas as pd

url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
users = pd.read_csv(url, sep='|')

print(users.columns)

print(users.groupby('occupation')['age'].mean())

In [ ]:
# Exercise XP 4

import pandas as pd

data1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

data2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['David', 'Eva', 'Frank']
})

# data3
data3 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Score': [85, 92, 78]
})

all_data_rows = pd.concat([data1, data2], ignore_index=True)
print(all_data_rows)

print()

all_data_col = pd.concat([data1, data2], axis=1)
print(all_data_col)

In [ ]:
# Exercise_XP_5

import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url, header=None)

iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

print(iris.isnull().sum())

In [ ]:
# Exercise_XP_6

import pandas as pd

df = pd.DataFrame({
    'evolution': ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
    'hp': [45, 39, 44, 45],
    'name': ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
    'pokedex': ['yes', 'no', 'yes', 'no'],
    'type': ['grass', 'fire', 'water', 'bug']
})

df = df[['name', 'type', 'hp', 'evolution', 'pokedex']]
print(df)

In [ ]:
# Exercise_XP_7

import pandas as pd

url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv'
baby_names = pd.read_csv(url)

print(baby_names.head(10))

baby_names = baby_names.drop(['Unnamed: 0', 'Id'], axis=1)

print(baby_names.columns)

baby_names = baby_names.drop(['Id'], axis=1)

In [ ]:
# Exercise_XP_8

import pandas as pd

temperature = [30, 31, 29, 32, 33, 34, 28, 27, 25, 35]
humidity = [80, 75, 70, 85, 90, 80, 75, 60, 65, 70]
wind_speed = [5, 6, 7, 8, 9, 4, 10, 5, 6, 7]

date_rng = pd.date_range(start='2021-01-01', end='2021-01-10', freq='D')

weather_data = pd.DataFrame({
    'Date': date_rng,
    'Temperature': temperature,
    'Humidity': humidity,
    'Wind_Speed': wind_speed
})

freq = pd.infer_freq(weather_data['Date'])
print("The frequency of the dataset is", freq + ".")

weather_data.set_index('Date', inplace=True)